version: 2.1
executors:
  node20:
    docker:
      - image: cimg/node:18.20.5

orbs:
  codecov: codecov/codecov@5.0.3

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: Validate orbs
          command: |
            export GITHUB_TOKEN=$GH_TOKEN
            curl --http1.1 -fLSs https://circle.ci/cli | DESTDIR=~ bash
            ~/circleci > /dev/null # first run checks for updates
            find . -name orb.yml -print0 | xargs -0 -I% ~/circleci orb validate %
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node20

    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Getting Code Coverage
          command: npm run test
      - codecov/upload
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

  release:
    executor: node20

    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      # note that npm release (semantic release) is done via github workflow
      - run:
          name: Semantic Orb Release
          command: |
            curl --http1.1 -fLSs https://circle.ci/cli | DESTDIR=~ bash
            ~/circleci > /dev/null # first run checks for updates
            node src/orb-release


workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          context: Project Helix
          requires:
            - build
          filters:
            branches:
              only: main
