version: 2.1

description: |
  Configures monitoring and alerting in New Relic, and links to Statuspage for public visibility of Project Helix services.

executors:
    node8:
        docker:
            - image: circleci/node:8

commands:
  config-env:
    description: Configures the build environment
    steps:
      - run:
          name: Configure Environment
          command: echo -e "LOG_LEVEL=info\n" > .env

  config-wsk:
    description: Sets the OpenWhisk properties
    steps:
      - run:
          name: Configure OpenWhisk
          command: echo -e "APIHOST=https://adobeioruntime.net\nNAMESPACE=helix\nAUTH=$WSK_AUTH\n" > ~/.wskprops

  monitoring:
    description: Sets up the monitoring
    parameters:
        targets:
            type: string
            description: "Comma-separated list of clouds the action is deployed to: universal, aws, google or adobeio."
        action_package:
            type: string
            default: "helix-services"
            description: The package name of the deployed action.
        action_name:
            type: string
            default: ""
            description: The name of the deployed action. Defaults to the package name.
        universal_host:
            type: string
            default: "helix-pages.anywhere.run"
            description: The host name of the universal runtime server.
        adobeio_host:
            type: string
            default: "adobeioruntime.net"
            description: The host name of the Adobe I/O Runtime server.
        adobeio_namespace:
            type: string
            default: "helix"
            description: The name of the Adobe I/O Runtime namespace the action is deployed to.
        aws_api:
            type: env_var_name
            default: HLX_AWS_API
            description: The AWS API to use.
        aws_region:
            type: env_var_name
            default: HLX_AWS_REGION
            description: The AWS region to use.
        google_project_id:
            type: env_var_name
            default: HLX_GOOGLE_PROJECT_ID
            description: The Google Cloud project ID to use.
        google_region:
            type: env_var_name
            default: HLX_GOOGLE_REGION
            description: The Google Cloud region to use.
        newrelic_auth:
            type: env_var_name
            default: NEWRELIC_AUTH
            description: The admin API key for your New Relic account. This is not the user API key!
        newrelic_name:
            type: string
            default: ""
            description: The name to be used for the New Relic monitor, alert policy and notification channel.
        newrelic_url:
            type: string
            default: ""
            description: The URL to monitor in New Relic.
        newrelic_type: 
            type: string
            default: ""
            description: The type of New Relic monitor (api or browser).
        newrelic_locations: 
            type: string
            default: ""
            description: The comma-separated list of locations to use.
        newrelic_frequency: 
            type: integer
            description: The frequency to trigger the monitor in minutes. Defaults to 15.
        newrelic_script: 
            type: string
            default: ""
            description: The path to the custom monitor script to use.
        newrelic_group_targets: 
            type: string
            default: ""
            description: The clouds to add to the group policy. Defaults to the first one.
        newrelic_group_policy: 
            type: string
            default: ""
            description: A collective alert policy in New Relic to add the monitor to.
        statuspage_auth:
            type: env_var_name
            default: STATUSPAGE_AUTH
            description: The user API key for your Statuspage account.
        statuspage_page_id:
            type: env_var_name
            default: STATUSPAGE_PAGE_ID
            description: The ID of the page to add components to in Statuspage.
        statuspage_incubator_page_id:
            type: env_var_name
            default: STATUSPAGE_INCUBATOR_PAGE_ID
            description: The ID of the page to add incubator components to in Statuspage.
        statuspage_name:
            type: string
            default: ""
            description: The name to be used for the Statuspage component.
        statuspage_group:
            type: string
            default: ""
            description: The name of the component group in Statuspage to add the component to.
        incubator:
            type: boolean
            default: false
            description: Flag as incubator project. Use this until ready for production.
        tool_path:
            type: string
            default: "./node_modules/.bin"
            description: The path to the monitoring automation tooling.
        action_namespace:
            type: string
            description: The name of the namespace where the action is deployed. Deprecated, use "adobeioNamespace" instead.
        aws:
            type: boolean
            description: Also monitor the action in AWS. Deprecated, use "targets" instead.
    steps:
      - run:
          name: Ensure Installation of CLI
          command: if [ ! -f ./node_modules/.bin/monitoringSetup ]; then npm i --no-save @adobe/helix-ops; fi
      - run:
          name: Monitoring Setup
          command: |
              # run monitoringSetup with params
              node << parameters.tool_path >>/monitoringSetup '{
                "toolPath":"<< parameters.tool_path >>",
                "actionNS":"<< parameters.action_namespace >>",
                "actionPackage":"<< parameters.action_package >>",
                "actionName":"<< parameters.action_name >>",
                "targets":"<< parameters.targets >>",
                "universalHost":"<< parameters.universal_host >>",
                "adobeioHost":"<< parameters.adobeio_host >>",
                "adobeioNS":"<< parameters.adobeio_namespace >>",
                "aws":"<< parameters.aws >>",
                "awsAPI":"<< parameters.aws_api >>",
                "awsRegion":"<< parameters.aws_region >>",
                "googleProjectID":"<< parameters.google_project_id >>",
                "googleRegion":"<< parameters.google_region >>",
                "incubator":"<< parameters.incubator >>",
                "nrName":"<< parameters.newrelic_name >>",
                "nrURL":"<< parameters.newrelic_url >>",
                "nrType":"<< parameters.newrelic_type >>",
                "nrLocations":"<< parameters.newrelic_locations >>",
                "nrFrequency":"<< parameters.newrelic_frequency >>",
                "nrScript":"<< parameters.newrelic_script >>",
                "nrGroupTargets":"<< parameters.newrelic_group_targets >>",
                "nrGroupPolicy":"<< parameters.newrelic_group_policy >>",
                "spName":"<< parameters.statuspage_name >>",
                "spGroup":"<< parameters.statuspage_group >>"
              }'
