version: 2.1

description: |
  Configures monitoring and alerting in New Relic, and links to Statuspage for public visibility of Project Helix services.

executors:
    node8:
        docker:
            - image: circleci/node:8

commands:
  config-env:
    description: Configures the build environment
    steps:
      - run:
          name: Configure Environment
          command: echo -e "LOG_LEVEL=info\n" > .env

  config-wsk:
    description: Sets the OpenWhisk properties
    steps:
      - run:
          name: Configure OpenWhisk
          command: echo -e "APIHOST=https://adobeioruntime.net\nNAMESPACE=helix\nAUTH=$WSK_AUTH\n" > ~/.wskprops

  monitoring:
    description: Sets up the monitoring
    parameters:
        tool_path:
            type: string
            default: "./node_modules/.bin"
            description: The path to the monitoring automation tooling
        action_namespace:
            type: string
            default: "helix"
            description: The name of the namespace where the action is deployed
        action_package:
            type: string
            default: "helix-services"
            description: The package name of the deployed action
        action_name:
            type: string
            default: ""
            description: The name of the deployed action
        aws:
            type: boolean
            default: false
            description: The action is also deployed in AWS
        aws_api:
            type: string
            default: ""
            description: The AWS API to use if AWS is set (defaults to $HLX_AWS_API)
        aws_region:
            type: string
            default: ""
            description: The AWS region to use if AWS is set (defaults to $HLX_AWS_REGION)
        incubator:
            type: boolean
            default: false
            description: Flag as incubator project
        newrelic_auth:
            type: env_var_name
            default: NEWRELIC_AUTH
            description: The admin's API key for your New Relic account (not the user API key!)
        newrelic_name:
            type: string
            default: ""
            description: The name to be used for the New Relic monitor, alert policy and notification channel
        newrelic_url:
            type: string
            default: ""
            description: The URL to monitor in New Relic
        newrelic_type: 
            type: string
            default: ""
            description: The type of monitor (api or browser)
        newrelic_locations: 
            type: string
            default: ""
            description: The comma-separated list of locations to use
        newrelic_frequency: 
            type: integer
            default: 15
            description: The frequency to trigger the monitor in minutes
        newrelic_script: 
            type: string
            default: ""
            description: The path to the custom monitor script to use
        newrelic_group_policy: 
            type: string
            default: ""
            description: A collective alert policy in New Relic to add the monitor to
        statuspage_auth:
            type: env_var_name
            default: STATUSPAGE_AUTH
            description: The API user key for your Statuspage account (this is the user API key)
        statuspage_page_id:
            type: env_var_name
            default: STATUSPAGE_PAGE_ID
            description: The ID of the page to add components to in Statuspage
        statuspage_incubator_page_id:
            type: env_var_name
            default: STATUSPAGE_INCUBATOR_PAGE_ID
            description: The ID of the page to add incubator components to in Statuspage
        statuspage_name:
            type: string
            default: ""
            description: The name to be used for the Statuspage component
        statuspage_group:
            type: string
            default: ""
            description: The name of the component group in Statuspage to add the new component to
    steps:
      - run:
          name: Ensure Installation of CLI
          command: if [ ! -f ./node_modules/.bin/newrelic ]; then npm i --no-save @adobe/helix-ops; fi
      - run:
          name: Monitoring Setup
          command: |
              # config params
              toolPath="<< parameters.tool_path >>"
              actionNS="<< parameters.action_namespace >>"
              actionPackage="<< parameters.action_package >>"
              actionName="<< parameters.action_name >>"
              aws=<< parameters.aws >>
              awApi="<< parameters.aws_api >>"
              awsRegion="<< parameters.aws_region >>"
              incubator=<< parameters.incubator >>
              nrAuth="<< parameters.newrelic_auth >>"
              nrName="<< parameters.newrelic_name >>"
              nrURL="<< parameters.newrelic_url >>"
              nrType="<< parameters.newrelic_type >>"
              nrLocations="<< parameters.newrelic_locations >>"
              nrFrequency="<< parameters.newrelic_frequency >>"
              nrScript="<< parameters.newrelic_script >>"
              nrGroupPolicy="<< parameters.newrelic_group_policy >>" 
              spAuth="<< parameters.statuspage_auth >>"
              spName="<< parameters.statuspage_name >>"
              spGroup="<< parameters.statuspage_group >>"
              spEmail=""

              # statuspage automation
              if [ "${spName}${spGroup}" != "" ]; then
                spEmail=`node ${toolPath}/statuspage setup --silent \
                  ${spName:+--name "${spName}"} \
                  ${spGroup:+--group "${spGroup}"} \
                  ${incubator:+--incubator ${incubator}} \
                  ${aws:+--aws ${aws}}`
              fi

              # new relic automation
              if [ "${actionName}" == "" ]; then
                # extract action name from package name
                actionName=`node -e "console.log(require('./package.json').name.replace('@adobe/helix-', ''))"`
              fi
              # use package version as action version
              actionVersion=`node -e "console.log(require('./package.json').version.match(/^[0-9]+/)[0])"`
              if [ "${nrURL}" == "" ]; then
                # assemble runtime url
                nrURL="https://adobeioruntime.net/api/v1/web/${actionNS}/${actionPackage}/${actionName}@v${actionVersion}/_status_check/healthcheck.json"
              fi
              if [ "${nrName}" == "" ]; then
                # use package name
                nrName=`node -e "console.log(require('./package.json').name)"`
              fi
              if [ $aws = true ]; then
                # add AWS url and name
                nrURL="${nrURL} --url https://${awsApi:-${HLX_AWS_API}}.execute-api.${awsRegion:-${HLX_AWS_REGION}}.amazonaws.com/${actionPackage}/${actionName}/v${actionVersion}/_status_check/healthcheck.json"
                nrName="${nrName} --name ${nrName}.aws"
              fi
              node ${toolPath}/newrelic setup --url ${nrURL} \
                ${nrName:+--name ${nrName}} \
                ${spEmail:+--email ${spEmail}} \
                ${nrType:+--type ${nrType}} \
                ${nrLocations:+--locations ${nrLocations}} \
                ${nrFrequency:+--frequency ${nrFrequency}} \
                ${nrScript:+--script "${nrScript}"} \
                ${nrGroupPolicy:+--group_policy "${nrGroupPolicy}"} \
                ${incubator:+--incubator ${incubator}}
